### ISSUE TITLE
SPI errors in examples for TTGO board

### ISSUE THREAD

**Issue by szczys** [russhughes/st7789_mpy#19]
The SPI setup for the TTGO examples appears to be incorrect:
```python
SoftSPI(2,baudrate=30000000,polarity=1,phase=1,sck=Pin(18),mosi=Pin(19))
```
 It's formatted like hardware SPI is being declared and throws an error when run:
```python
>>> import ttgo_scroll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ttgo_scroll.py", line 103, in <module>
  File "ttgo_scroll.py", line 33, in main
TypeError: extra keyword arguments given
```
The error is caused by the hardware SPI selector at the beginning (2). If it is removed we get another curious error.
```python
ValueError: must specify all of sck/mosi/miso
```
The call shouldn't require an miso declaration since [the constructor in the standard defaults to None](https://docs.micropython.org/en/latest/library/machine.SPI.html). But I cannot figure out a syntax that allows the declaration without specifying a valid pin for MISO. I have it working by declaring pin 21 but it's not ideal:
```python
SoftSPI(baudrate=30000000,polarity=1,phase=1,sck=Pin(18),mosi=Pin(19),miso=Pin(21))
```
Anyone know how to declare SoftSPI without occupying a GPIO for no reason? I'm going to submit a pull request for the examples but it would be nice to get this pin assignment problem worked out.

Incidentally, did they screw up the hardware design of these boards? The data-in for the screen should be connected to IO23 [to use hardware VSPI](https://docs.micropython.org/en/latest/esp32/quickref.html#hardware-spi-bus). Instead, IO19 is connected (that should be MISO) and IO23 is connected to reset. Oops?

**Comment by szczys** [comment]
This chip has a wonderful pin MUX feature so we are able to use the hardware SPI even though the screen is not wired to the right VSPI pins. It means we don't get the absolute fastest performance for SPI, but it's noticeably faster than SoftSPI. I've submitted PR #21 to update TTGO examples to use this. It looks like russhughes' implementation had the parameters correct for hardware SPI but was initializing them by calling SoftSPI so this was a simple fix.

I have found one bug along the way:
1. Copy two examples to /pyboard, one that uses hardware SPI and the other that uses software SPI
2. Run repl an import the hardware spi example: **works**
3. ctrl-c to break execution and import the software spi example: **works**
4. ctrl-c to break execution and import the hardware spi example: **doesn't work**, just returns to the repl prompt

I'm unsure of the cause. I thought maybe `SPI.init()` needed to be called to reset pins but that doesn't seem to fix the problem. No error is thrown so it's difficult to troubleshoot, and all it takes to get things working is a soft reset (ctrl-d) of repl or a hard reset or power cycle of the board. I consider this enough of an edge case that it doesn't need to be fixed, I'm just happy to have the speed of hardware spi.
